# Generated by Django 5.0.7 on 2024-07-15 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_um", "0002_tabela1_tabela2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tabela_A",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a1", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Tabela_B",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("b1", models.CharField(max_length=10)),
                (
                    "b2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_um.tabela_a",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tabela_C",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c1", models.CharField(max_length=10)),
                (
                    "c2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_um.tabela_a",
                    ),
                ),
            ],
        ),
    ]
