# Generated by Django 5.0.7 on 2024-07-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_um", "0003_tabela_a_tabela_b_tabela_c"),
    ]

    operations = [
        migrations.CreateModel(
            name="TabelaTeste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("um", models.CharField(max_length=10)),
                ("dois", models.CharField(blank=True, max_length=10)),
                ("tres", models.CharField(max_length=10, verbose_name="Campo3")),
                ("quatro", models.CharField(help_text="descrição", max_length=10)),
                (
                    "cinco",
                    models.CharField(
                        choices=[
                            ("MG", "Minas Gerais"),
                            ("SP", "São Paulo"),
                            ("BA", "Bahia"),
                        ],
                        default="",
                        max_length=2,
                    ),
                ),
                (
                    "seis",
                    models.CharField(
                        error_messages={"unique": "ja tem esse valor no banco."},
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
