# Generated by Django 5.0.7 on 2024-07-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_um', '0004_tabelateste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musica', models.CharField(max_length=50)),
                ('cantor', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Musica2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musica', models.CharField(max_length=50)),
                ('cantor', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='D_Caracteres',
        ),
        migrations.DeleteModel(
            name='D_Datas_E_Horas',
        ),
        migrations.DeleteModel(
            name='D_Numeros_Com_Virgula',
        ),
        migrations.DeleteModel(
            name='D_Numeros_Inteiros',
        ),
        migrations.DeleteModel(
            name='D_Numeros_Inteiros_Positivos',
        ),
        migrations.DeleteModel(
            name='tabela1',
        ),
        migrations.DeleteModel(
            name='tabela2',
        ),
        migrations.RemoveField(
            model_name='tabela_c',
            name='c2',
        ),
        migrations.RemoveField(
            model_name='tabela_b',
            name='b2',
        ),
        migrations.DeleteModel(
            name='TabelaTeste',
        ),
        migrations.DeleteModel(
            name='Tabela_C',
        ),
        migrations.DeleteModel(
            name='Tabela_A',
        ),
        migrations.DeleteModel(
            name='Tabela_B',
        ),
    ]
